export enum DIRECTION_NAME {
    LEFT = 'LEFT',
    RIGHT = 'RIGHT',
    BOTTOM = 'BOTTOM',
    TOP = 'TOP',
    TOP_RIGHT = 'TOP_RIGHT',
    BOTTOM_RIGHT = 'BOTTOM_RIGHT',
    TOP_LEFT = 'TOP_LEFT',
    BOTTOM_LEFT = 'BOTTOM_LEFT',
}

export const DIRECTION = {
    '[1,0]' : DIRECTION_NAME.RIGHT,
    '[-1,0]': DIRECTION_NAME.LEFT,
    '[0,1]': DIRECTION_NAME.BOTTOM,
    '[0,-1]': DIRECTION_NAME.TOP,
    '[1,-1]': DIRECTION_NAME.TOP_RIGHT,
    '[1,1]': DIRECTION_NAME.BOTTOM_RIGHT,
    '[-1,-1]': DIRECTION_NAME.TOP_LEFT,
    '[-1,1]': DIRECTION_NAME.BOTTOM_LEFT,
};
